### ISSUE TITLE
support public/private addresses for all infrastructure elements

### ISSUE THREAD

**Issue by kormat** [netsec-ethz/scion#815]
Currently we have entries like this:

```
  bs1-11-1:
    Addr: x.x.x.x
    Port: 30054
```

These should instead be changed to something like:

```
  bs1-11-1:
    PublicAddr: x.x.x.x
    PublicPort: 30054
    BindAddr: y.y.y.y
    BindPort: zzzz
```

The public addr/port must be defined, and are what everything will use when connecting to that element. The bind addr/port are both optional, and if defined are what the element actually binds to. If either is undefined, the public equivalent is used instead.
