### ISSUE TITLE
Incorrect topology parsing in case of multiple border routers on the same IP

### ISSUE THREAD

**Issue by ercanucan** [netsec-ethz/scion#932]
While attempting to deploy multiple border routers on the same IP, we ran into an issue which looks like the topology file is not parsed correctly. As an example, part of a topology file may look as below. In such a case, the `br1-1-4` would parse the `Addr` and `Port` correctly. However, it would think that the `Interface` block it needs to use is the same as that of `br1-1-2`, eventually leading to an address already in use error.
```
  br1-1-2:
    Addr: 203.0.113.0/32
    Interface:
      Addr: 203.0.113.0/32
      Bandwidth: 1000
      IFID: 2
      ISD_AS: 1-2
      LinkType: CHILD
      MTU: 1472
      ToAddr: 203.0.113.1/32
      ToUdpPort: 50000
      UdpPort: 50000
    Port: 31042
  br1-1-4:
    Addr: 203.0.113.0/32
    Interface:
      Addr: 203.0.113.0/32
      Bandwidth: 1000
      IFID: 4
      ISD_AS: 2-21
      LinkType: ROUTING
      MTU: 1472
      ToAddr: 203.0.113.3/32
      ToUdpPort: 50001
      UdpPort: 50001
    Port: 31043
```
Relevant supervisord config files can be found in the following attachments:

[supervisord_conf_br1-1-2.txt](https://github.com/netsec-ethz/scion/files/569154/supervisord_conf_br1-1-2.txt)

[supervisord_conf_br1-1-4.txt](https://github.com/netsec-ethz/scion/files/569155/supervisord_conf_br1-1-4.txt)
